L17
CaptainPhilipp/tn_rails pull request #9
Opened 2017-04-06 22:46 UTC by CaptainPhilipp

2017-04-11 07:57 UTC, vkurennov requested changes

2017-04-11 07:57 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +  def set_ticket_context(params_)
Особого смысла передавать параметры как аргумент нет, ведь это же обычный инстанс-метод, он и так имеет доступ к методу `params`.

2017-04-11 07:57 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    set_ticket_context(ticket_params)
Вот это нужно будет только для `new`, значит и вызывать это можно в `else`

2017-04-11 07:57 UTC, vkurennov commented on app/controllers/trains_controller.rb
> +  def search
Поиск лучше отдельным контроллером сделать, имхо. Да, формально мы ищем поезда, но сам по себе поиск - это отдельная страница и самостоятельный ресурс. Он может усложняться, поэтому лучше его отделить от контроллера поездов.

2017-04-11 07:57 UTC, vkurennov commented on app/helpers/trains_helper.rb
>  module TrainsHelper
Хелперы нужны для видов, именно для этого и есть папка helpers, если нужен какой-то модуль только для контроллера, то лучше его поместить в папку `controllers/concerns`

2017-04-11 07:57 UTC, vkurennov commented on app/models/railway_station.rb
> +  scope :ordered_by_route, lambda {
Сейчас принято указывать `->`, а не `lambda`

2017-04-11 09:33 UTC, CaptainPhilipp commented on config/routes.rb
> +    get 'new/:train_id/:departure_id/:arrival_id', to: 'tickets#new', on: :collection, as: :new
выбирая между передачей параметров через создание формы с `hidden_field` для каждой строки каждого поезда (т.е. в html на каждый найденный поезд будут дублироваться одни и те же `hidden_field_tag` с `departure_id`, и `arrival_id`)
и кастомным роутом, содержащим все необходимые аргументы, я выбрал роут.
Может есть вариант получше в данной ситуации?

2017-04-11 09:33 UTC, CaptainPhilipp commented on app/controllers/tickets_controller.rb
> +  def set_ticket_context(params_)
я сделал так, без фильтра и с передачей `params` через аргументы, тк в одном экшене эти данные берутся через `params.require(:ticket)`, в другом - просто из `params` (тк параметры передаются туда уже не из формы, а через роут)

собсно потому аргументу и добавил в конце `_` что бы указать его возможное отличие от `params`

2017-04-11 09:33 UTC, CaptainPhilipp commented on app/helpers/trains_helper.rb
>  module TrainsHelper
эту штуку я перенёс сюда из контроллера т.к. она использовалась не только в самом контроллере, но и в его вьюхах.

2017-04-11 09:33 UTC, CaptainPhilipp commented on app/models/railway_station.rb
> +  scope :ordered_by_route, lambda {
а меня вроде рубокоп когда-то поправлял, говорил для многострочников юзать lambda. может что-то не уловил... посмотрю.

2017-04-11 11:57 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +  def set_ticket_context(params_)
ок, принято

2017-04-11 11:58 UTC, vkurennov commented on app/helpers/trains_helper.rb
>  module TrainsHelper
А зачем во вьюхах стронг-параметры?

2017-04-11 11:59 UTC, vkurennov commented on app/models/railway_station.rb
> +  scope :ordered_by_route, lambda {
Хм, может быть, но тогда и do end надо использовать, а не фигруные скобки

2017-04-11 11:59 UTC, vkurennov commented on config/routes.rb
> +    get 'new/:train_id/:departure_id/:arrival_id', to: 'tickets#new', on: :collection, as: :new
С роутами лучше, имхо

2017-04-11 12:38 UTC, CaptainPhilipp commented on app/models/railway_station.rb
> +  scope :ordered_by_route, lambda {
а с do end вообще мистика:
Еще в BlackJack писал `lambda do /n end`, и всё правильно, 'на стиле' - интерпретатор доволен, коп доволен, стайлгайд одобряет.
А уже недавно в рельсах на скоупах вдруг полетели ошибки - требует скобок даже на многострочные блоки.
вообще, это на столько странно что сам себе сейчас не верю, буду перепроверять.
Но точно помню что он грубо ругался > я удивился, поменял > работает.

2017-04-11 19:31 UTC, CaptainPhilipp commented on app/models/railway_station.rb
> +  scope :ordered_by_route, lambda {
проверил - do end  кидает ошибку мол пытаюсь сделать прок без блока.
а на стрелочку коп жалуется. на скобочки - стайлгайд.

2017-04-11 19:35 UTC, CaptainPhilipp commented on app/helpers/trains_helper.rb
>  module TrainsHelper
а, точно, я же их уже убрал из вьюх...
забыл перенеси метод обратно в контроллер под приват. ему там уютнее.

2017-04-12 08:31 UTC, vkurennov approved these changes

2017-04-12 08:31 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +  def trains_by_terminal_stations
Не стоили делать кастомный экшн, да еще и с таким длинным и неудобным названием. Досаточно было, например, new или show.

2017-04-12 08:31 UTC, vkurennov commented on app/models/railway_station.rb
> +  scope :ordered_by_route, lambda {
Ок, пусть так остается

2017-04-12 08:31 UTC, vkurennov commented on config/routes.rb
> +  namespace :searches do
Это не неймспейс должен быть, а ресурс. И раз он в одном экземпляре существует, то лучше его и объявлять как `resource :search`

2017-04-12 18:37 UTC, merged